CREATE DATABASE browse;
USE browse;

CREATE TABLE catalogue (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50) UNIQUE,
	description VARCHAR(200),
	author VARCHAR(50),
	publisher VARCHAR(50),
	picture VARCHAR(10000000),
	text VARCHAR(10000000)
)

INSERT INTO catalogue(title,author,publisher,description,text,picture) VALUES ('The Boat People','Sharon Bala','Trial',"When a rusty cargo ship carrying Mahindan and five hundred fellow refugees from Sri Lanka's bloody civil war reaches Vancouver's shores, the young father thinks he and his six-year-old son can finally start a new life.","When a rusty cargo ship carrying Mahindan and five hundred fellow refugees from Sri Lanka's bloody civil war reaches Vancouver's shores, the young father thinks he and his six-year-old son can finally start a new life. Instead, the group is thrown into a detention processing center, with government officials and news headlines speculating that among the \"boat people\" are members of a separatist militant organization responsible for countless suicide attacks—and that these terrorists now pose a threat to Canada's national security. As the refugees become subject to heavy interrogation, Mahindan begins to fear that a desperate act taken in Sri Lanka to fund their escape may now jeopardize his and his son's chance for asylum.\n
Told through the alternating perspectives of Mahindan; his lawyer, Priya, a second-generation Sri Lankan Canadian who reluctantly represents the refugees; and Grace, a third-generation Japanese Canadian adjudicator who must decide Mahindan's fate as evidence mounts against him, The Boat People is a spellbinding and timely novel that provokes a deeply compassionate lens through which to view the current refugee crisis.
",""),
																			  ('The Bone Mother',"David Demchuk","Trial","Three neighbouring villages on the Ukrainian/Romanian border are the final refuge for the last of the mythical creatures of Eastern Europe.","
Description: Three neighbouring villages on the Ukrainian/Romanian border are the final refuge for the last of the mythical creatures of Eastern Europe. Now, on the eve of the war that may eradicate their kind―and with the ruthless Night Police descending upon their sanctuary―they tell their stories and confront their destinies: \n
The Rusalka, the beautiful vengeful water spirit who lives in lakes and ponds and lures men and children to their deaths;\n
The Vovkulaka, who changes from her human form into that of a wolf and hides with her kind deep in the densest forests;\n
The Strigoi, a revenant who feasts on blood and twists the minds of those who love, serve and shelter him;\n
The Dvoynik, an apparition that impersonates its victim and draws him into a web of evil in order to free itself;\n
And the Bone Mother, a skeletal crone with iron teeth who lurks in her house in the heart of the woods, and cooks and eats those who fail her vexing challenges.\n
Eerie and unsettling like the best fairy tales, these incisor-sharp portraits of ghosts, witches, sirens, and seers―and the mortals who live at their side and in their thrall―will chill your marrow and tear at your heart.",""),
																			  ("American War: A novel","Omar El Akkad","Trial","An audacious and powerful debut novel: a second American Civil War, a devastating plague, and one family caught deep in the middle—a story that asks what might happen if America were to turn its most devastating policies and deadly weapons upon itself","An audacious and powerful debut novel: a second American Civil War, a devastating plague, and one family caught deep in the middle—a story that asks what might happen if America were to turn its most devastating policies and deadly weapons upon itself.\n
Sarat Chestnut, born in Louisiana, is only six when the Second American Civil War breaks out in 2074. But even she knows that oil is outlawed, that Louisiana is half underwater, and that unmanned drones fill the sky. When her father is killed and her family is forced into Camp Patience for displaced persons, she begins to grow up shaped by her particular time and place. But not everyone at Camp Patience is who they claim to be. Eventually Sarat is befriended by a mysterious functionary, under whose influence she is turned into a deadly instrument of war. The decisions that she makes will have tremendous consequences not just for Sarat but for her family and her country, rippling through generations of strangers and kin alike.",""),
																			  ("Salt, Fat, Acid, Heat: Mastering the Elements of Good Cooking","Samin Nosrat","Trial","A visionary new master class in cooking that distills decades of professional experience into just four simple elements, from the woman declared “America’s next great cooking teacher” by Alice Waters.","A visionary new master class in cooking that distills decades of professional experience into just four simple elements, from the woman declared “America’s next great cooking teacher” by Alice Waters.\n
In the tradition of The Joy of Cooking and How to Cook Everything comes Salt, Fat, Acid, Heat, an ambitious new approach to cooking by a major new culinary voice. Chef and writer Samin Nosrat has taught everyone from professional chefs to middle school kids to author Michael Pollan to cook using her revolutionary, yet simple, philosophy. Master the use of just four elements—Salt, which enhances flavor; Fat, which delivers flavor and generates texture; Acid, which balances flavor; and Heat, which ultimately determines the texture of food—and anything you cook will be delicious. By explaining the hows and whys of good cooking, Salt, Fat, Acid, Heat will teach and inspire a new generation of cooks how to confidently make better decisions in the kitchen and cook delicious meals with any ingredients, anywhere, at any time.\n
Echoing Samin’s own journey from culinary novice to award-winning chef, Salt, Fat Acid, Heat immediately bridges the gap between home and professional kitchens. With charming narrative, illustrated walkthroughs, and a lighthearted approach to kitchen science, Samin demystifies the four elements of good cooking for everyone. Refer to the canon of 100 essential recipes—and dozens of variations—to put the lessons into practice and make bright, balanced vinaigrettes, perfectly caramelized roast vegetables, tender braised meats, and light, flaky pastry doughs.\n
Featuring 150 illustrations and infographics that reveal an atlas to the world of flavor by renowned illustrator Wendy MacNaughton, Salt, Fat, Acid, Heat will be your compass in the kitchen. Destined to be a classic, it just might be the last cookbook you’ll ever need. ", ""),
																			  ("Candy Is Magic: Real Ingredients, Modern Recipes","Jami Curl","Trial","
Description: Chai Tea Lollipops, Honey and Sea Salt Marshmallows, Chocolate Pretzel Caramels, Cherry Cola Gumdrops—this is not your average candy, or your average candy book. Candy-maker extraordinaire Jami Curl breaks down candy making into its most precise and foolproof steps.","
Description: Chai Tea Lollipops, Honey and Sea Salt Marshmallows, Chocolate Pretzel Caramels, Cherry Cola Gumdrops—this is not your average candy, or your average candy book. Candy-maker extraordinaire Jami Curl breaks down candy making into its most precise and foolproof steps. No guess work, no expensive equipment, just the best possible ingredients and stop-you-in-your-tracks-brilliant flavor combinations. She begins with the foundations of candy; how to create delicious syrups, purees, and “magic dusts” that are the building blocks for making lollipops, caramels, marshmallows, and gummy candy. But even more ingeniously, these syrups, purees, and magic dusts can be used to make a myriad of other sweet confections such as Strawberry Cream Soda, Peanut Butter Hot Fudge, Marshmallow Brownies, and Popcorn Ice Cream. And what to do with all your homemade candy? Jami has your covered, with instructions for making candy garlands, tiny candy-filled pinatas, candy ornaments, and more—you are officially party ready.\n 
But this is just the tip of the deliciously sweet iceberg--packed with nearly 200 recipes, careful step-by-step instruction, tips for guaranteed success, and flavor guides to help you come up with own unique creations—Candy is Magic is a candy call to action!",""),
																			  ("Sing, Unburied, Sing: A Novel","Jesmyn Ward","Trial","In Jesmyn Ward’s first novel since her National Book Award–winning Salvage the Bones, this singular American writer brings the archetypal road novel into rural twenty-first-century America.","Jojo is thirteen years old and trying to understand what it means to be a man. He doesn’t lack in fathers to study, chief among them his Black grandfather, Pop. But there are other men who complicate his understanding: his absent White father, Michael, who is being released from prison; his absent White grandfather, Big Joseph, who won’t acknowledge his existence; and the memories of his dead uncle, Given, who died as a teenager.\n
",""),
																			  ("Distributed Systems: Concepts and Design","George Coulouris","Trial","Broad and up-to-date coverage of the principles and practice in the fast moving area of Distributed Systems","Distributed Systems provides students of computer science and engineering with the skills they will need to design and maintain software for distributed applications. It will also be invaluable to software engineers and systems designers wishing to understand new and future developments in the field.\n
From mobile phones to the Internet, our lives depend increasingly on distributed systems linking computers and other devices together in a seamless and transparent way. The fifth edition of this best-selling text continues to provide a comprehensive source of material on the principles and practice of distributed computer systems and the exciting new developments based on them, using a wealth of modern case studies to illustrate their design and development. The depth of coverage will enable readers to evaluate existing distributed systems and design new ones.
",""),
																			  ("Distributed Systems","Maarten van Steen","Trial","For this third edition of 'Distributed Systems,' the material has been thoroughly revised and extended, integrating principles and paradigms into nine chapters:","For this third edition of 'Distributed Systems' the material has been thoroughly revised and extended, integrating principles and paradigms into nine chapters: 1. Introduction 2. Architectures 3. Processes 4. Communication 5. Naming 6. Coordination 7. Replication 8. Fault tolerance 9. Security A separation has been made between basic material and more specific subjects. The latter have been organized into boxed sections, which may be skipped on first reading. To assist in understanding the more algorithmic parts, example programs in Python have been included. The examples in the book leave out many details for readability, but the complete code is available through the book's Website, hosted at www.distributed-systems.net. A personalized digital copy of the book is available for free, as well as a printed version through Amazon.com.
",""),
																			  ("Kubernetes: Up and Running: Dive into the Future of Infrastructure","Kelsey Hightower","Trial","Legend has it that Google deploys over two billion application containers a week. How’s that possible?","Legend has it that Google deploys over two billion application containers a week. How’s that possible? Google revealed the secret through a project called Kubernetes, an open source cluster orchestrator (based on its internal Borg system) that radically simplifies the task of building, deploying, and maintaining scalable distributed systems in the cloud. This practical guide shows you how Kubernetes and container technology can help you achieve new levels of velocity, agility, reliability, and efficiency.
",""),
																			  ("The Outsider: A Novel ","Stephen King","Trial","An unspeakable crime. A confounding investigation. At a time when the King brand has never been stronger, he has delivered one of his most unsettling and compulsively readable stories","An unspeakable crime. A confounding investigation. At a time when the King brand has never been stronger, he has delivered one of his most unsettling and compulsively readable stories.\n
An eleven-year-old boy’s violated corpse is found in a town park. Eyewitnesses and fingerprints point unmistakably to one of Flint City’s most popular citizens. He is Terry Maitland, Little League coach, English teacher, husband, and father of two girls. Detective Ralph Anderson, whose son Maitland once coached, orders a quick and very public arrest. Maitland has an alibi, but Anderson and the district attorney soon add DNA evidence to go with the fingerprints and witnesses. Their case seems ironclad.\n
As the investigation expands and horrifying answers begin to emerge, King’s propulsive story kicks into high gear, generating strong tension and almost unbearable suspense. Terry Maitland seems like a nice guy, but is he wearing another face? When the answer comes, it will shock you as only Stephen King can.
","")



